// src/pages/api/appointments.ts
// Handles appointment-request form submissions and pushes them into Shopmonkey.
// DO NOT edit this file per client — update src/lib/email.config.ts and the
// SHOPMONKEY_* env vars instead.
//
// Flow:
//   1. Validate the submission.
//   2. Best-effort: create a customer + appointment in Shopmonkey.
//   3. Always: email the shop the full request (safety net if Shopmonkey fails).
//   4. Always: email the customer a "we received your request" confirmation.
//   5. Slack alert on email send failure (via sendWithAlert).
//
// The Shopmonkey appointment is created UNCONFIRMED — the shop reviews and
// confirms the real time in Shopmonkey. The customer is told it's a request.

import type { APIRoute } from 'astro';
import { Resend } from 'resend';
import { EMAIL_CONFIG } from '~/lib/email.config';
import { sendWithAlert } from '~/lib/form-alert';
import { createAppointmentRequest, shopmonkeyConfigured } from '~/lib/shopmonkey';

const resend = new Resend(import.meta.env.RESEND_API_KEY);
const FORM_ALERT_SLACK_URL = import.meta.env.FORM_ALERT_SLACK_URL;

export const POST: APIRoute = async ({ request }) => {
  try {
    const data = await request.formData();
    const name    = data.get('name')?.toString().trim()    ?? '';
    const email   = data.get('email')?.toString().trim()   ?? '';
    const phone   = data.get('phone')?.toString().trim()   ?? '';
    const service = data.get('service')?.toString().trim() ?? '';
    const vehicle = data.get('vehicle')?.toString().trim() ?? '';
    const date    = data.get('date')?.toString().trim()    ?? '';
    const time    = data.get('time')?.toString().trim()    ?? '';
    const message = data.get('message')?.toString().trim() ?? '';
    const source  = data.get('source')?.toString().trim()  ?? '';

    if (!name || !email || !phone || !date || !time) {
      return new Response(
        JSON.stringify({ error: 'Name, email, phone, date and time are required.' }),
        { status: 400 }
      );
    }

    const [firstName, ...rest] = name.split(' ');
    const lastName = rest.join(' ');
    const humanSlot = `${date} at ${time}`;

    // 1. Push into Shopmonkey (best-effort — never blocks the lead).
    let sm = { ok: false, detail: 'Shopmonkey not attempted.' } as Awaited<
      ReturnType<typeof createAppointmentRequest>
    >;
    if (shopmonkeyConfigured) {
      sm = await createAppointmentRequest({
        firstName: firstName || name,
        lastName,
        email,
        phone,
        service,
        vehicle,
        preferredDate: date,
        preferredTime: time,
        message,
      });
    }

    // 2. Notify the shop — always, with the full request + Shopmonkey status.
    const smLine = shopmonkeyConfigured
      ? `<p style="color:${sm.ok ? '#127a2e' : '#b00020'}"><strong>Shopmonkey:</strong> ${sm.detail}</p>`
      : '';
    try {
      await sendWithAlert(
        { client: EMAIL_CONFIG.brand.name, formName: 'Appointment request — notification', slackWebhookUrl: FORM_ALERT_SLACK_URL },
        () => resend.emails.send({
          from: EMAIL_CONFIG.from.notifications,
          to: EMAIL_CONFIG.notify,
          subject: `New appointment request: ${name} — ${humanSlot}`,
          html: `
            <h2>New Appointment Request</h2>
            <p><strong>Name:</strong> ${name}</p>
            <p><strong>Email:</strong> ${email}</p>
            <p><strong>Phone:</strong> ${phone}</p>
            <p><strong>Service:</strong> ${service || '—'}</p>
            <p><strong>Vehicle:</strong> ${vehicle || '—'}</p>
            <p><strong>Requested time:</strong> ${humanSlot}</p>
            ${message ? `<p><strong>Notes:</strong></p><p>${message.replace(/\n/g, '<br>')}</p>` : ''}
            ${smLine}
            ${source ? `<hr><p style="color:#888;font-size:13px"><strong>Source</strong><br>${source.replace(/\n/g, '<br>')}</p>` : ''}
          `,
        })
      );
    } catch (err) {
      console.error('Resend notify error:', err);
    }

    // 3. Confirm to the customer.
    try {
      await sendWithAlert(
        { client: EMAIL_CONFIG.brand.name, formName: 'Appointment request — confirmation', slackWebhookUrl: FORM_ALERT_SLACK_URL },
        () => resend.emails.send({
          from: EMAIL_CONFIG.from.hello,
          to: email,
          subject: EMAIL_CONFIG.copy.appointment.confirmSubject,
          html: EMAIL_CONFIG.copy.appointment.confirmBody(firstName || name, humanSlot),
        })
      );
    } catch (err) {
      console.error('Resend confirm error:', err);
    }

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Appointments API error:', err);
    return new Response(
      JSON.stringify({ error: 'Something went wrong. Please try again.' }),
      { status: 500 }
    );
  }
};
