// src/pages/api/appointment.ts
// Handles the booking/estimate/question form (#bkForm on /appointments) and
// pushes the request into Shopmonkey as a Workflow-board ORDER (customer +
// vehicle + order in "Customer Pool & Appointments").
// DO NOT edit this file per client — tune copy in src/lib/email.config.ts and
// the SHOPMONKEY_* / RESEND_* env vars.
//
// Flow:
//   1. Validate (name + phone required; the form has no email field).
//   2. Best-effort: create a Shopmonkey customer + vehicle + workflow order.
//   3. Always: email the shop the full request (safety net if Shopmonkey fails).
//   4. Slack-alert on email send failure (via sendWithAlert).

import type { APIRoute } from 'astro';
import { Resend } from 'resend';
import { EMAIL_CONFIG } from '~/lib/email.config';
import { sendWithAlert , notifySubmission, fieldsFromFormData } from '~/lib/form-alert';
import { createLead, shopmonkeyConfigured } from '~/lib/shopmonkey';

export const prerender = false; // server route — must not be statically built

// Read keys at module scope, but DON'T construct the Resend client here —
// `new Resend("")` throws, which would crash the whole function with a non-JSON
// 500 before any error handling runs. Construct it lazily inside the handler.
const RESEND_API_KEY = import.meta.env.RESEND_API_KEY;
// Slack destination. FORM_SLACK_WEBHOOK is this client's own channel and takes
// precedence for BOTH submissions and failures; SLACK_WEBHOOK is the
// shared fallback for clients without a channel of their own.
const SLACK_WEBHOOK =
  import.meta.env.FORM_SLACK_WEBHOOK || import.meta.env.FORM_ALERT_SLACK_URL;

// Internal labels shown on the Shopmonkey board card + shop notification email.
// Keys MUST stay book/question to match the form's intent values; estimate is
// retained as a harmless fallback (the form no longer sends it).
const INTENT_LABEL: Record<string, string> = {
  book: 'Schedule an appointment',
  estimate: 'Get an estimate',
  question: 'General inquiry',
}

// Email/heading per intent so a general inquiry doesn't read as an appointment.
const INTENT_HEADING: Record<string, string> = {
  book: 'New Appointment Request',
  estimate: 'New Estimate Request',
  question: 'New General Inquiry',
}

export const POST: APIRoute = async ({ request }) => {
  try {
    const data = await request.formData();

    // Honeypot: humans never see the off-screen "website" field. If it's filled,
    // it's a bot — return success so it doesn't retry, but process nothing.
    if (data.get('website')?.toString().trim()) {
      return new Response(JSON.stringify({ success: true }), { status: 200 });
    }

    const name    = data.get('name')?.toString().trim()    ?? '';
    const phone   = data.get('phone')?.toString().trim()   ?? '';
    const email   = data.get('email')?.toString().trim()   ?? '';
    const make    = data.get('make')?.toString().trim()    ?? '';
    const modelYear = data.get('model')?.toString().trim()  ?? ''; // "2019 Q5"
    const vin     = data.get('vin')?.toString().trim().toUpperCase() ?? '';
    const message = data.get('message')?.toString().trim() ?? '';
    const date    = data.get('date')?.toString().trim()    ?? '';
    const time    = data.get('time')?.toString().trim()    ?? '';
    const intentRaw = data.get('intent')?.toString().trim() ?? 'book';
    const returning = data.get('returning')?.toString().trim() ?? '';
    const referral  = data.get('referral')?.toString().trim()  ?? ''; // "How did you hear" — new customers only

    // Split a 4-digit year out of the combined "Model & year" field.
    const yearMatch = modelYear.match(/\b(19|20)\d{2}\b/);
    const year = yearMatch ? Number(yearMatch[0]) : undefined;
    const model = yearMatch ? modelYear.replace(yearMatch[0], '').trim() : modelYear;
    const intent  = INTENT_LABEL[intentRaw] ? intentRaw : 'book';

    if (!name || !phone || !email) {
      return new Response(
        JSON.stringify({ error: 'Please add your name, phone, and email.' }),
        { status: 400 }
      );
    }

    const [firstName, ...rest] = name.split(' ');
    const lastName = rest.join(' ');
    const vehicle = [make, modelYear].filter(Boolean).join(' '); // human-readable, keeps year
    const intentLabel = INTENT_LABEL[intent];
    // New customers must provide a VIN (enforced on the form); surface the
    // answer so the shop knows whether to ask for VIN/plate on intake.
    const customerStatus = returning === 'yes' ? 'Current customer' : returning === 'no' ? 'New customer' : '';
    // Order title on the Workflow board.
    const leadTitle = `${intentLabel}${vehicle ? ` — ${vehicle}` : ''}${message ? `: ${message}` : ''}`.slice(0, 140);

    // 1. Push into Shopmonkey (best-effort — never blocks the lead).
    let sm = { ok: false, detail: 'Shopmonkey not attempted.' } as Awaited<
      ReturnType<typeof createLead>
    >;
    if (shopmonkeyConfigured) {
      sm = await createLead({
        firstName: firstName || name,
        lastName,
        email,
        phone,
        service: leadTitle,
        vehicle,
        make,
        model,
        year,
        vin,
        preferredDate: date,
        preferredTime: time,
        message: `Intent: ${intentLabel}${customerStatus ? `\nCustomer: ${customerStatus}` : ''}${referral ? `\nHeard about us: ${referral}` : ''}${message ? `\n${message}` : ''}`,
      });
    }

    // 2. Notify the shop — always, with the full request + Shopmonkey status.
    const smLink = sm.ok
      ? ` <a href="https://app.shopmonkey.io/" style="color:#127a2e">Open Shopmonkey →</a>`
      : '';
    const smLine = shopmonkeyConfigured
      ? `<p style="color:${sm.ok ? '#127a2e' : '#b00020'}"><strong>Shopmonkey:</strong> ${sm.detail}${smLink}</p>`
      : '';
    if (RESEND_API_KEY) {
      try {
        const resend = new Resend(RESEND_API_KEY);
        // The error is held rather than thrown so the Slack log below still runs;
        // it is re-thrown straight after, so the caller behaves exactly as before.
        let notifyError: unknown = null;
        try {
          await sendWithAlert(
            { client: EMAIL_CONFIG.brand.name, formName: 'Appointment request — notification', slackWebhookUrl: SLACK_WEBHOOK },
            () => resend.emails.send({
              from: EMAIL_CONFIG.from.notifications,
              to: EMAIL_CONFIG.notify,
              subject: `New ${intentLabel.toLowerCase()}: ${name}${vehicle ? ` (${vehicle})` : ''}`,
              html: `
                <h2>${INTENT_HEADING[intent] || 'New Request'}</h2>
                <p><strong>Intent:</strong> ${intentLabel}</p>
                <p><strong>Name:</strong> ${name}</p>
                <p><strong>Phone:</strong> ${phone}</p>
                <p><strong>Email:</strong> ${email}</p>
                ${customerStatus ? `<p><strong>Customer:</strong> ${customerStatus}</p>` : ''}
                ${referral ? `<p><strong>How they heard about us:</strong> ${referral}</p>` : ''}
                ${intent === 'book' ? `
                <p><strong>Vehicle:</strong> ${vehicle || '—'}</p>
                ${vin ? `<p><strong>VIN:</strong> ${vin}</p>` : ''}
                <p><strong>Preferred drop-off date:</strong> ${date || '— (none given)'}</p>
                <p><strong>Preferred drop-off time:</strong> ${time || '— (no preference)'}</p>` : (vehicle ? `<p><strong>Vehicle:</strong> ${vehicle}</p>` : '')}
                ${message ? `<p><strong>${intent === 'book' ? 'What it needs' : 'Message'}:</strong></p><p>${message.replace(/\n/g, '<br>')}</p>` : ''}
                ${smLine}
              `,
            })
          );
        } catch (err) {
          notifyError = err;
        }

        // Log the submission to the client's Slack channel, whether or not the
        // email went out. When the send failed this is the *only* surviving copy
        // of what someone typed, so it posts either way and says which it is.
        await notifySubmission({
          client: EMAIL_CONFIG.brand.name,
          slackWebhookUrl: SLACK_WEBHOOK,
          route: 'Appointment request',
          delivered: !notifyError,
          fields: fieldsFromFormData(data),
        });

        if (notifyError) throw notifyError;
      } catch (err) {
        console.error('Resend notify error:', err);
      }
    } else {
      console.warn('RESEND_API_KEY not set — skipping shop notification email');
    }

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Appointment API error:', err);
    return new Response(
      JSON.stringify({ error: 'Something went wrong. Please try again, or call us at (210) 399-1172.' }),
      { status: 500 }
    );
  }
};
