// src/pages/api/appointment.ts
// Handles the booking/estimate/question form (#bkForm on /appointments) and
// pushes the request into Shopmonkey (customer + unconfirmed appointment).
// DO NOT edit this file per client — tune copy in src/lib/email.config.ts and
// the SHOPMONKEY_* / RESEND_* env vars.
//
// Flow:
//   1. Validate (name + phone required; the form has no email field).
//   2. Best-effort: create a Shopmonkey customer + unconfirmed appointment.
//   3. Always: email the shop the full request (safety net if Shopmonkey fails).
//   4. Slack-alert on email send failure (via sendWithAlert).
//
// The Shopmonkey appointment is created UNCONFIRMED — a tech reviews it and
// confirms the real time, exactly as the page's "we confirm by text" copy says.

import type { APIRoute } from 'astro';
import { Resend } from 'resend';
import { EMAIL_CONFIG } from '~/lib/email.config';
import { sendWithAlert } from '~/lib/form-alert';
import { createAppointmentRequest, shopmonkeyConfigured } from '~/lib/shopmonkey';

export const prerender = false; // server route — must not be statically built

// Read keys at module scope, but DON'T construct the Resend client here —
// `new Resend("")` throws, which would crash the whole function with a non-JSON
// 500 before any error handling runs. Construct it lazily inside the handler.
const RESEND_API_KEY = import.meta.env.RESEND_API_KEY;
const FORM_ALERT_SLACK_URL = import.meta.env.FORM_ALERT_SLACK_URL;

const INTENT_LABEL: Record<string, string> = {
  book: 'Book a service',
  estimate: 'Get an estimate',
  question: 'Ask a question',
};

/** YYYY-MM-DD for "tomorrow" — placeholder slot when no date is given. */
function tomorrowDate(): string {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  return d.toISOString().slice(0, 10);
}

export const POST: APIRoute = async ({ request }) => {
  try {
    const data = await request.formData();
    const name    = data.get('name')?.toString().trim()    ?? '';
    const phone   = data.get('phone')?.toString().trim()   ?? '';
    const make    = data.get('make')?.toString().trim()    ?? '';
    const model   = data.get('model')?.toString().trim()   ?? '';
    const message = data.get('message')?.toString().trim() ?? '';
    const date    = data.get('date')?.toString().trim()    ?? '';
    const intentRaw = data.get('intent')?.toString().trim() ?? 'book';
    const intent  = INTENT_LABEL[intentRaw] ? intentRaw : 'book';

    if (!name || !phone) {
      return new Response(
        JSON.stringify({ error: 'Please add your name and a phone number.' }),
        { status: 400 }
      );
    }

    const [firstName, ...rest] = name.split(' ');
    const lastName = rest.join(' ');
    const vehicle = [make, model].filter(Boolean).join(' ');
    const intentLabel = INTENT_LABEL[intent];
    // Appointment name shown in Shopmonkey's scheduler.
    const apptName = `${intentLabel}${vehicle ? ` — ${vehicle}` : ''}${message ? `: ${message}` : ''}`.slice(0, 140);

    // 1. Push into Shopmonkey (best-effort — never blocks the lead).
    let sm = { ok: false, detail: 'Shopmonkey not attempted.' } as Awaited<
      ReturnType<typeof createAppointmentRequest>
    >;
    if (shopmonkeyConfigured) {
      sm = await createAppointmentRequest({
        firstName: firstName || name,
        lastName,
        email: '', // this form has no email field
        phone,
        service: apptName,
        vehicle,
        preferredDate: date || tomorrowDate(), // placeholder slot if none given
        preferredTime: '09:00',
        message: `Intent: ${intentLabel}${date ? '' : ' (no preferred date given)'}${message ? `\n${message}` : ''}`,
      });
    }

    // 2. Notify the shop — always, with the full request + Shopmonkey status.
    const smLine = shopmonkeyConfigured
      ? `<p style="color:${sm.ok ? '#127a2e' : '#b00020'}"><strong>Shopmonkey:</strong> ${sm.detail}</p>`
      : '';
    if (RESEND_API_KEY) {
      try {
        const resend = new Resend(RESEND_API_KEY);
        await sendWithAlert(
          { client: EMAIL_CONFIG.brand.name, formName: 'Appointment request — notification', slackWebhookUrl: FORM_ALERT_SLACK_URL },
          () => resend.emails.send({
            from: EMAIL_CONFIG.from.notifications,
            to: EMAIL_CONFIG.notify,
            subject: `New ${intentLabel.toLowerCase()}: ${name}${vehicle ? ` (${vehicle})` : ''}`,
            html: `
              <h2>New Appointment Request</h2>
              <p><strong>Intent:</strong> ${intentLabel}</p>
              <p><strong>Name:</strong> ${name}</p>
              <p><strong>Phone:</strong> ${phone}</p>
              <p><strong>Vehicle:</strong> ${vehicle || '—'}</p>
              <p><strong>Preferred date:</strong> ${date || '— (none given)'}</p>
              ${message ? `<p><strong>What it needs:</strong></p><p>${message.replace(/\n/g, '<br>')}</p>` : ''}
              ${smLine}
            `,
          })
        );
      } catch (err) {
        console.error('Resend notify error:', err);
      }
    } else {
      console.warn('RESEND_API_KEY not set — skipping shop notification email');
    }

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Appointment API error:', err);
    return new Response(
      JSON.stringify({ error: 'Something went wrong. Please try again, or call us at (210) 399-1172.' }),
      { status: 500 }
    );
  }
};
