// src/pages/api/lead.ts
// Handles primary lead/inquiry form submissions (name, email, company, goal, etc.).
// DO NOT edit this file per client — update src/lib/email.config.ts instead.

import type { APIRoute } from 'astro';
import { Resend } from 'resend';
import mailchimp from '@mailchimp/mailchimp_marketing';
import { EMAIL_CONFIG } from '~/lib/email.config';
import { sendWithAlert , notifySubmission, fieldsFromFormData } from '~/lib/form-alert';

const resend = new Resend(import.meta.env.RESEND_API_KEY);
// Astro reads env via import.meta.env, so pass the Slack URL explicitly.
// Slack destination. FORM_SLACK_WEBHOOK is this client's own channel and takes
// precedence for BOTH submissions and failures; SLACK_WEBHOOK is the
// shared fallback for clients without a channel of their own.
const SLACK_WEBHOOK =
  import.meta.env.FORM_SLACK_WEBHOOK || import.meta.env.FORM_ALERT_SLACK_URL;

if (EMAIL_CONFIG.mailchimp.enabled) {
  mailchimp.setConfig({
    apiKey: import.meta.env.MAILCHIMP_API_KEY,
    server: import.meta.env.MAILCHIMP_SERVER_PREFIX,
  });
}

export const POST: APIRoute = async ({ request }) => {
  try {
    const data    = await request.formData();
    const name    = data.get('name')?.toString().trim()    ?? '';
    const email   = data.get('email')?.toString().trim()   ?? '';
    const company = data.get('company')?.toString().trim() ?? '';
    const phone   = data.get('phone')?.toString().trim()   ?? '';
    const goal    = data.get('goal')?.toString().trim()    ?? '';
    const source  = data.get('source')?.toString().trim()  ?? '';

    if (!email || !name) {
      return new Response(JSON.stringify({ error: 'Name and email are required.' }), { status: 400 });
    }

    // Internal notification
    try {
      // The error is held rather than thrown so the Slack log below still runs;
      // it is re-thrown straight after, so the caller behaves exactly as before.
      let notifyError: unknown = null;
      try {
        await sendWithAlert(
          { client: EMAIL_CONFIG.brand.name, formName: 'Lead form — notification', slackWebhookUrl: SLACK_WEBHOOK },
          () => resend.emails.send({
            from: EMAIL_CONFIG.from.notifications,
            to: EMAIL_CONFIG.notify,
            subject: `New lead: ${company || name}`,
            html: `
              <h2>New Lead Form Submission</h2>
              <p><strong>Name:</strong> ${name}</p>
              <p><strong>Email:</strong> ${email}</p>
              ${company ? `<p><strong>Company:</strong> ${company}</p>` : ''}
              ${phone   ? `<p><strong>Phone:</strong> ${phone}</p>` : ''}
              ${goal    ? `<p><strong>Goal:</strong> ${goal}</p>` : ''}
              ${source  ? `<hr><p style="color:#888;font-size:13px"><strong>Source</strong><br>${source.replace(/\n/g, '<br>')}</p>` : ''}
            `,
          })
        );
      } catch (err) {
        notifyError = err;
      }

      // Log the submission to the client's Slack channel, whether or not the
      // email went out. When the send failed this is the *only* surviving copy
      // of what someone typed, so it posts either way and says which it is.
      await notifySubmission({
        client: EMAIL_CONFIG.brand.name,
        slackWebhookUrl: SLACK_WEBHOOK,
        route: 'Lead form',
        delivered: !notifyError,
        fields: fieldsFromFormData(data),
      });

      if (notifyError) throw notifyError;
    } catch (err) {
      console.error('Resend notify error:', err);
    }

    // Confirmation to sender
    try {
      await sendWithAlert(
        { client: EMAIL_CONFIG.brand.name, formName: 'Lead form — confirmation', slackWebhookUrl: SLACK_WEBHOOK },
        () => resend.emails.send({
          from: EMAIL_CONFIG.from.hello,
          to: email,
          subject: EMAIL_CONFIG.copy.lead.confirmSubject,
          html: EMAIL_CONFIG.copy.lead.confirmBody(name, company, EMAIL_CONFIG.brand.url),
        })
      );
    } catch (err) {
      console.error('Resend confirm error:', err);
    }

    // Always add leads to Mailchimp
    if (EMAIL_CONFIG.mailchimp.enabled) {
      try {
        await mailchimp.lists.addListMember(import.meta.env.MAILCHIMP_AUDIENCE_ID, {
          email_address: email,
          status: 'subscribed',
          merge_fields: {
            FNAME:   name.split(' ')[0],
            LNAME:   name.split(' ').slice(1).join(' '),
            COMPANY: company,
          },
          tags: [...EMAIL_CONFIG.mailchimp.defaultTags, 'lead-form'],
        });
      } catch (err: any) {
        console.error('Mailchimp lead error:', err?.response?.body ?? err);
      }
    }

    return new Response(JSON.stringify({ success: true }), { status: 200 });
  } catch (err) {
    console.error('Lead API error:', err);
    return new Response(JSON.stringify({ error: 'Something went wrong. Please try again.' }), { status: 500 });
  }
};
